function createProduct() {
	if (localStorage.getItem('List-products') === null) {
		let productArray = [
			{ productId: 10000, categories: 'Văn học', author: 'Nguyễn Hồng', publishingHouse: 'NXB Văn Học', img: 'images/sachvanhoc/BiVo_NguyenHong.jpg', name: 'Bỉ Vỏ', price: 349000, description: 'Một tác phẩm văn học nghiên cứu những chủ đề tinh tế, mang đến một câu chuyện hấp dẫn được sáng tác bởi tài năng của Nguyễn Hồng.' },
			{ productId: 10001, categories: 'Văn học', author: 'Phan Đức Lộc', publishingHouse: 'NXB Văn Học', img: 'images/sachvanhoc/ToiSeBay.jpg', name: 'Tôi Sẽ Bay', price: 290000, description: ' Phan Đức Lộc dẫn độ độc giả vào một hành trình sâu sắc thông qua "Tôi Sẽ Bay," khám phá những chiều sâu của trải nghiệm và hoài bão con người.' },
			{ productId: 10002, categories: 'Văn học', author: 'H.BEERCHER STOWE', publishingHouse: 'NXB Văn Học', img: 'images/sachvanhoc/TupLeuBacTom.jpg', name: 'Túp Lều Bác Tôm', price: 453000, description: 'H.BEERCHER STOWE tạo nên một câu chuyện hấp dẫn trong "Túp Lều Bác Tôm," mang đến độc giả cái nhìn sâu sắc về thế giới đầy nhân văn và phê phán xã hội.' },
			{ productId: 10003, categories: 'Văn học', author: 'Vũ Trọng Phụng', publishingHouse: 'NXB Văn Học', img: 'images/sachvanhoc/SoDo_VuTrongPhung.jpg', name: 'Số Đỏ', price: 264000, description: ' "Số Đỏ" của Vũ Trọng Phụng là một kiệt tác văn học Việt Nam, khám phá những vấn đề xã hội với bản lĩnh và kỹ thuật kể chuyện tinh tế.' },
			{ productId: 10004, categories: 'Văn học', author: 'Nguyễn Công Hoan', publishingHouse: 'NXB Văn Học', img: 'images/sachvanhoc/BuocDuongCung_NguyenCongHoan.jpg', name: 'Bước Đường Cùng', price: 249000, description: ' "Bước Đường Cùng" của Nguyễn Công Hoan đưa độc giả vào một hành trình suy tư, khám phá sâu sắc về cuộc sống và bản chất con người.' },
			{ productId: 10005, categories: 'Văn học', author: 'Trần Đình Sử', publishingHouse: 'NXB Văn Học', img: 'images/sachvanhoc/DocVanHocVan_TranDinhSu.jpg', name: 'Đọc Văn Học Văn', price: 162000, description: '"Đọc Văn Học Văn" của Trần Đình Sử cung cấp cho độc giả một bộ sưu tập những tác phẩm văn học tuyệt vời, thể hiện kỹ thuật kể chuyện tài năng và cái nhìn sâu sắc của tác giả.' },
			{ productId: 10006, categories: 'Văn học', author: 'Sơn Tùng', publishingHouse: 'NXB Văn Học', img: 'images/sachvanhoc/CuocChiaLyTrenBenNhaRong_SonTung.jpg', name: 'Cuộc Chia Ly Trên Bến Nhà Rồng', price: 206000, description: ' "Cuộc Chia Ly Trên Bến Nhà Rồng" của Sơn Tùng mời gọi độc giả vào một câu chuyện cảm động, khám phá tình yêu, sự chia lìa và tinh thần con người.' },
			{ productId: 10007, categories: 'Văn học', author: 'Trần Thúy Lành', publishingHouse: 'NXB Văn Học', img: 'images/sachvanhoc/LongSon_TranThuyLanh.gif', name: 'Lồng Son', price: 381000, description: ' "Lồng Son" của Trần Thúy Lành là một kiệt tác văn học, kết hợp chặt chẽ các chủ đề về bản sắc, tình yêu và kỳ vọng của xã hội.' },
			{ productId: 10008, categories: 'Văn học', author: 'Nguyễn Công Hoan', publishingHouse: 'NXB Văn Học', img: 'images/sachvanhoc/TruyenNganChonLoc_NguyenCongHoan.png', name: 'Truyện Ngắn Chọn Lọc', price: 390000, description: 'Đắm chìm trong câu chuyện phong phú của Nguyễn Công Hoan với "Truyện Ngắn Chọn Lọc," một bộ sưu tập các truyện ngắn được tuyển chọn kỹ lưỡng.' },
			{ productId: 10009, categories: 'Văn học', author: 'Vẽ Hạnh Phúc', publishingHouse: 'NXB Văn Học', img: 'images/sachvanhoc/ToBinhYenVeHanhPhuc.png', name: 'Tô Bình Yên -Vẽ Hạnh Phúc-', price: 170000, description: ' "Tô Bình Yên -Vẽ Hạnh Phúc-" của Vẽ Hạnh Phúc là một khám phá thơ ca về việc tìm kiếm bình yên và hạnh phúc giữa những thách thức của cuộc sống.' },
			{ productId: 10010, categories: 'Văn học', author: 'Hồ Xuân Hương', publishingHouse: 'NXB Văn Học', img: 'images/sachvanhoc/TuyenTapThoHoXuanHuong.jpg', name: 'Thơ Hồ Xuân Huong', price: 132000, description: 'Dấn thân vào thế giới thơ của Hồ Xuân Hương với bộ sưu tập này, tôn vinh vẻ đẹp và sự thông thái của một trong những nhà thơ nổi tiếng nhất của Việt Nam.' },
			{ productId: 10011, categories: 'Văn học', author: 'Hội đồng KHXH TPHCM', publishingHouse: 'NXB Tổng hợp TPHCM', img: 'images/sachvanhoc/DiaChiVanHoaTPHCM.jpg', name: 'Địa Chí Văn Hoá TPHCM', price: 81000, description: ' "Địa Chí Văn Hoá TPHCM" mang đến một cái nhìn toàn diện về cảnh văn hóa của Thành phố Hồ Chí Minh, được thể hiện thông qua lời chuyên gia am hiểu của Hội đồng KHXH TPHCM.' },
			{ productId: 10012, categories: 'Văn học', author: 'Phạm Thị Thanh Nga - Nguyễn Thị Thanh Hiền - Trần Tiến Thành', publishingHouse: 'NXB Giáo Dục Việt Nam', img: 'images/sachvanhoc/BoiDuongHSGMonNguVanLop9.jpg', name: 'Bồi Dưỡng HSG Môn Ngữ Văn Lớp 9', price: 194000, description: 'Một tài liệu giáo dục được thiết kế để nuôi dưỡng học sinh giỏi môn văn, "Bồi Dưỡng HSG Môn Ngữ Văn Lớp 9" mang lại cái nhìn và bài tập quý báu.' },
			{ productId: 10013, categories: 'Văn học', author: 'Nguyễn Thành Thi', publishingHouse: 'NXB Tổng hợp TPHCM', img: 'images/sachvanhoc/ChuyenDeHocTapNguVan11.png', name: 'Chuyên Đề Học Tập Ngữ Văn 11', price: 181000, description: '"Chuyên Đề Học Tập Ngữ Văn 11" của Nguyễn Thành Thi là một hướng dẫn học tập chuyên sâu dành cho học sinh, mang đến phân tích sâu sắc và bài tập liên quan đến văn học.' },
			{ productId: 10014, categories: 'Văn học', author: 'Phương Lựu', publishingHouse: 'NXB Tổng hợp TPHCM', img: 'images/sachvanhoc/LiLuanVanHoc_tap1.jpg', name: 'Lí Luận Văn Học Tập 1', price: 352000, description: 'Đắm chìm vào khía cạnh lý luận văn học với "Lí Luận Văn Học Tập 1" của Phương Lựu, một hướng dẫn toàn diện về lý luận văn học.' },
			{ productId: 10015, categories: 'Văn học', author: 'Lã Nhâm Thìn', publishingHouse: 'NXB Tổng hợp TPHCM', img: 'images/sachvanhoc/GiaoTrinhVanHocTrungDaiVietNam.jpg', name: 'Giáo Trình Văn Học Trung Đại Việt Nam Tập 1', price: 297000, description: 'Khám phá bức tranh phong phú của văn học cổ điển Việt Nam với "Giáo Trình Văn Học Trung Đại Việt Nam Tập 1" của Lã Nhâm Thìn, một tài liệu quan trọng cho những người yêu văn học.' },


			{ productId: 11000, categories: 'Thiếu nhi', author: 'Lewis Carroll, MinaLima', publishingHouse: 'NXB Văn Học', img: 'images/sachthieunhi/AliceOXuSoThanTien_Phan3.jpg', name: 'Alice ở xứ sở thần tiên', price: 449000, description: '"Alice ở xứ sở thần tiên" là một cuộc phiêu lưu tuyệt vời của cô bé Alice qua thế giới kỳ bí, được tái hiện sinh động qua bản minh họa của MinaLima.' },
			{ productId: 11001, categories: 'Thiếu nhi', author: 'Kelin Hawkes, Michael Jan Black ', publishingHouse: 'NXB Văn Học', img: 'images/sachthieunhi/ChickenCheeks.jpg', name: 'Chicken Cheeks', price: 549000, description: ' "Chicken Cheeks" là một cuốn sách thú vị dành cho thiếu nhi với những hình ảnh hài hước và câu chuyện về những chú gà độc đáo.' },
			{ productId: 11002, categories: 'Thiếu nhi', author: 'La Hi', publishingHouse: 'NXB Văn Học', img: 'images/sachthieunhi/ChiecKhauTrangBietDem.jpg', name: 'Chiếc Khẩu Trang Biết Đếm', price: 469000, description: '"Chiếc Khẩu Trang Biết Đếm" là một cuốn sách hấp dẫn giúp trẻ rèn kỹ năng đếm thông qua những hình ảnh sinh động và câu chuyện thú vị.' },
			{ productId: 11003, categories: 'Thiếu nhi', author: 'Phi Tân', publishingHouse: 'NXB Văn Học', img: 'images/sachthieunhi/CoTichCuaBa.jpg', name: 'Cổ Tích Của Ba', price: 395000,	description: '"Cổ Tích Của Ba" mang đến cho độc giả những câu chuyện truyền thống dân gian, là nguồn cảm hứng tuyệt vời cho tình thân gia đình.' },
			{ productId: 11004, categories: 'Thiếu nhi', author: 'T-Books', publishingHouse: 'NXB Văn Học', img: 'images/sachthieunhi/CoVaCao.jpg', name: 'Cò Và Cáo', price: 255000, description: '"Cò Và Cáo" là một câu chuyện nhỏ về tình bạn giữa hai loài động vật khác nhau, nhấn mạnh giá trị của sự đa dạng và hiểu biết.' },
			{ productId: 11005, categories: 'Thiếu nhi', author: 'Bùi Phương Tâm', publishingHouse: 'NXB Văn Học', img: 'images/sachthieunhi/DungLaTet.jpg', name: 'Đúng Là Tết', price: 267000, description: '"Đúng Là Tết" là một câu chuyện ấm áp về ý nghĩa của Tết và tình cảm gia đình, kể qua góc nhìn đáng yêu của các nhân vật.' },
			{ productId: 11006, categories: 'Thiếu nhi', author: 'Antoine De Saint-Exupery', publishingHouse: 'NXB Văn Học', img: 'images/sachthieunhi/HoangTuBe.jpg', name: 'Hoàng Tử Bé', price: 162000, description: ' "Hoàng Tử Bé" là một câu chuyện triết lý về tình bạn và ý nghĩa của cuộc sống, được yêu thích trên khắp thế giới.' },
			{ productId: 11007, categories: 'Thiếu nhi', author: 'Michiko Kaito', publishingHouse: 'NXB Văn Học', img: 'images/sachthieunhi/MaruVaHatDua.jpg', name: 'Maru Và Hạt Dưa', price: 193000, description: ' "Maru Và Hạt Dưa" là một câu chuyện đáng yêu về tình bạn và lòng nhân ái, với hình ảnh đẹp và thông điệp tích cực.' },
			{ productId: 11008, categories: 'Thiếu nhi', author: 'Nhiều Tác Giả', publishingHouse: 'NXB Văn Học', img: 'images/sachthieunhi/NgoanNgoan.png', name: 'Ngoan Ngoãn', price: 324000, description: '"Ngoan Ngoãn" là một tuyển tập những câu chuyện nhỏ dành cho thiếu nhi, giúp trẻ học những bài học quý báu về đạo đức và tình cảm.' },
			{ productId: 11009, categories: 'Thiếu nhi', author: 'Rosie Dickins', publishingHouse: 'NXB Văn Học', img: 'images/sachthieunhi/NhungCauChuyenCoTichHayNhatTheGioi.jpg', name: 'Những Câu Chuyện Cổ Tích Hay Nhất Thế Giới', price: 126000, description: '"Những Câu Chuyện Cổ Tích Hay Nhất Thế Giới" là một bộ sưu tập tuyệt vời của các câu chuyện kỳ diệu từ khắp nơi trên thế giới.' },
			{ productId: 11010, categories: 'Thiếu nhi', author: 'Edmodo De Amicis', publishingHouse: 'NXB Văn Học', img: 'images/sachthieunhi/NhungTamLongCaoCa.jpg', name: 'Những Tấm Lòng Cao Cả', price: 93000, description: ' "Những Tấm Lòng Cao Cả" là một câu chuyện hữu ích về lòng nhân ái, sự hiểu biết và tình người, phản ánh tâm huyết và tố chất nhân văn.' },
			{ productId: 11011, categories: 'Thiếu nhi', author: 'Nguyên Hương', publishingHouse: 'NXB Văn Học', img: 'images/sachthieunhi/NhungTruyenHayVietChoThieuNhi.jpg', name: 'Những Truyện Hay Viết Cho Thiếu Nhi ', price: 64000, description: 'Cuốn sách "Những Truyện Hay Viết Cho Thiếu Nhi" của tác giả Nguyên Hương là một bộ sưu tập độc đáo, tinh tế và đầy màu sắc, hứa hẹn mang đến cho độc giả những trải nghiệm đọc sáng tạo và thú vị.' },
			{ productId: 11012, categories: 'Thiếu nhi', author: 'Nguyễn Thị Thanh Bình', publishingHouse: 'NXB Văn Học', img: 'images/sachthieunhi/QueNgoai.jpg', name: 'Quê Ngoại', price: 173000, description: 'Hành trình trở về nguồn cội, nhắc nhở về giá trị của quê hương và tình cảm gia đình.' },
			{ productId: 11013, categories: 'Thiếu nhi', author: 'Huỳnh Thái Ngọc', publishingHouse: 'NXB Văn Học', img: 'images/sachthieunhi/ThoBayMau.jpg', name: 'Thỏ Bảy Màu Và Những Người Nghĩ Nó Là Bạn', price: 76000, description: 'Câu chuyện về sự đa dạng và tôn trọng, kể qua cuộc phiêu lưu của thỏ Bảy Màu trong thế giới động vật.' },
			{ productId: 11014, categories: 'Thiếu nhi', author: 'Vẽ Hạnh Phúc', publishingHouse: 'NXB Văn Học', img: 'images/sachthieunhi/ToBinhYenVeHanhPhuc.png', name: 'Tô Bình Yên -Vẽ Hạnh Phúc-', price: 170000, description: 'Cuốn sách mang đến thông điệp tích cực về sự bình yên và hạnh phúc trong cuộc sống hàng ngày.' },
			{ productId: 11014, categories: 'Thiếu nhi', author: 'Lê Đức Dương', publishingHouse: 'NXB Văn Học', img: 'images/sachthieunhi/cavoi.jpg', name: 'Ca Voi Eren đến Hòn Mun', price: 216000, description: 'Hành trình kỳ diệu của ca voi Eren đến Hòn Mun, kết hợp giáo dục về môi trường và tình yêu thích thú.' },


			{ productId: 12000, categories: 'Sách giáo khoa', author: 'Lewis Carroll, MinaLima', publishingHouse: 'NXB Văn Học', img: 'images/sachgiaokhoa/AmNhac1.jpg', name: 'Sách âm nhạc 1', price: 49000, description: 'Sách âm nhạc 1 là tài liệu giáo trình chất lượng dành cho học sinh, biên soạn bởi các tác giả nổi tiếng. Cuốn sách giúp học sinh hiểu sâu về nền âm nhạc và cung cấp kiến thức cần thiết để phát triển sự hiểu biết và đam mê với âm nhạc.' },
			{ productId: 12001, categories: 'Sách giáo khoa', author: 'Hồ Ngọc Khải', publishingHouse: 'NXB Văn Học', img: 'images/sachgiaokhoa/AmNhac8.png', name: 'Âm Nhạc 8', price: 17000, description: 'Cuốn sách Âm Nhạc 8 là nguồn tư duy học thuật đầy đủ và chi tiết về nền âm nhạc, giúp học sinh lớp 8 nắm bắt kiến thức cơ bản và phát triển sự đam mê với nghệ thuật âm nhạc.' },
			{ productId: 12002, categories: 'Sách giáo khoa', author: 'Hồ Ngọc Khải', publishingHouse: 'NXB Văn Học', img: 'images/sachgiaokhoa/AmNhac10.png', name: 'Âm Nhạc 10', price: 24000, description: 'Sách Âm Nhạc 10 là nguồn tài liệu học tập linh hoạt, giúp học sinh lớp 10 hiểu rõ hơn về lịch sử âm nhạc và các khái niệm quan trọng khác trong môn nghệ thuật này.' },
			{ productId: 12003, categories: 'Sách giáo khoa', author: 'Hồ Ngọc Khải', publishingHouse: 'NXB Văn Học', img: 'images/sachgiaokhoa/amnhac11.png', name: 'Âm Nhạc 11', price: 36000, description: 'Cuốn sách Âm Nhạc 11 giúp học sinh nắm vững kiến thức sâu rộng về âm nhạc, từ các giai điệu cơ bản đến các phong cách và dòng nhạc đa dạng.' },
			{ productId: 12004, categories: 'Sách giáo khoa', author: 'Bộ Giáo dục và đào tạo', publishingHouse: 'NXB Văn Học', img: 'images/sachgiaokhoa/HinhHoc11.jpg', name: 'Hình Học 11', price: 58000, description: 'Sách Hình Học 11 là nguồn tư liệu học tập quan trọng, giúp học sinh nắm bắt kiến thức căn bản và phức tạp của môn học này.' },
			{ productId: 12005, categories: 'Sách giáo khoa', author: 'Cao Cự Giác', publishingHouse: 'NXB Văn Học', img: 'images/sachgiaokhoa/hoahoc10.png', name: 'Hóa Học 10', price: 25000, description: 'Sách Hóa Học 10 cung cấp kiến thức chất lượng, giúp học sinh lớp 10 hiểu sâu về thế giới của hóa học và ứng dụng của nó trong cuộc sống hàng ngày.' },
			{ productId: 12006, categories: 'Sách giáo khoa', author: 'Nguyễn Thị Nhung - Nguyễn Xuân Tiên', publishingHouse: 'NXB Văn Học', img: 'images/sachgiaokhoa/MiThuat6.jpg', name: 'Mĩ Thuật 6', price: 19000, description: 'Cuốn sách Mĩ Thuật 6 là nguồn cẩm nang hữu ích giúp học sinh lớp 6 phát triển khả năng sáng tạo và thẩm mỹ, thông qua việc khám phá các kỹ thuật và ý tưởng nghệ thuật cơ bản.' },
			{ productId: 12007, categories: 'Sách giáo khoa', author: 'Nguyễn Thị May', publishingHouse: 'NXB Văn Học', img: 'images/sachgiaokhoa/MiThuat8.png', name: 'Mĩ Thuật 8', price: 47000, description: 'Sách Mĩ Thuật 8 là hướng dẫn chi tiết về các khái niệm và kỹ thuật mĩ thuật, giúp học sinh lớp 8 phát triển khả năng vẽ và sáng tạo nghệ thuật.' },
			{ productId: 12008, categories: 'Sách giáo khoa', author: 'Bùi Mạnh Hùng', publishingHouse: 'NXB Văn Học', img: 'images/sachgiaokhoa/NguVan6.jpg', name: 'Ngữ Văn 6 (tập 2)', price: 52000, description: 'Cuốn sách Ngữ Văn 6 (tập 2) là nguồn tư liệu quan trọng giúp học sinh lớp 6 phát triển kỹ năng ngôn ngữ và hiểu biết văn hóa.' },
			{ productId: 12009, categories: 'Sách giáo khoa', author: 'Nguyễn Thành Thi', publishingHouse: 'NXB Văn Học', img: 'images/sachgiaokhoa/NguVan10.png', name: 'Ngữ Văn 10 (tập 1)', price: 31000,	description: 'Sách Ngữ Văn 10 (tập 1) giúp học sinh lớp 10 nắm bắt kiến thức văn học cơ bản và phát triển khả năng đọc hiểu, sáng tạo văn bản.' },
			{ productId: 12010, categories: 'Sách giáo khoa', author: 'Trần Nam Dũng', publishingHouse: 'NXB Văn Học', img: 'images/sachgiaokhoa/Toan1.jpg', name: 'Toán 1', price: 14000,	description: 'Cuốn sách Toán 1 là nguồn kiến thức cơ bản và lý thuyết, giúp học sinh lớp 1 hiểu và áp dụng các khái niệm toán học đơn giản.' },
			{ productId: 12011, categories: 'Sách giáo khoa', author: 'Bộ Giáo dục và đào tạo', publishingHouse: 'NXB Văn Học', img: 'images/sachgiaokhoa/Toan4.jpg', name: 'Toán 4', price: 32000,	description: ' Sách Toán 4 cung cấp bài giảng và bài tập đa dạng, giúp học sinh lớp 4 phát triển kỹ năng giải toán và hiểu sâu về các khái niệm toán học cơ bản.' },
			{ productId: 12012, categories: 'Sách giáo khoa', author: 'Bộ Giáo dục và đào tạo', publishingHouse: 'NXB Văn Học', img: 'images/sachgiaokhoa/Toan9.jpg', name: 'Toán 9 (tập 1)', price: 45000,	description: 'Cuốn sách Toán 9 (tập 1) là nguồn tài liệu học tập đầy đủ, giúp học sinh lớp 9 nắm vững kiến thức và kỹ năng giải toán.' },
			{ productId: 12013, categories: 'Sách giáo khoa', author: 'Trần Nam Dũng', publishingHouse: 'NXB Văn Học', img: 'images/sachgiaokhoa/Toan4tap1.png', name: 'Toán 4 (tập 1)', price: 29000,	description: ' Sách Toán 4 (tập 1) giúp học sinh lớp 4 nắm vững kiến thức căn bản và phát triển khả năng giải toán một cách linh hoạt.' },
			{ productId: 12014, categories: 'Sách giáo khoa', author: 'Đỗ Đức Thái', publishingHouse: 'NXB Văn Học', img: 'images/sachgiaokhoa/Toan10tap1.png', name: 'Toán 10 (tập 1)', price: 34000,	description: 'Cuốn sách Toán 10 (tập 1) giúp học sinh lớp 10 nắm bắt kiến thức cơ bản và phức tạp của môn học này.' },
			{ productId: 12015, categories: 'Sách giáo khoa', author: 'Lê Thị Hạnh Dung', publishingHouse: 'NXB Văn Học', img: 'images/sachgiaokhoa/vatli9.jpg', name: 'Vật Lí 9', price: 18000,	description: 'Sách Vật Lí 9 cung cấp kiến thức về các định luật vật lý cơ bản và giúp học sinh lớp 9 hiểu rõ về thế giới vật lý xung quanh.' },



			{ productId: 13000, categories: 'Sách ngoại ngữ', author: 'Lewis Carroll, MinaLima', publishingHouse: 'NXB Văn Học', img: 'images/sachngoaingu/301CauDamThoaiTiengHoa.jpg', name: '301 câu đàm thoại tiếng Hoa', price: 449000, description: '"301 câu đàm thoại tiếng Hoa" là nguồn tài liệu hữu ích cho những người muốn học và cải thiện khả năng giao tiếp tiếng Hoa thông qua các mô phỏng câu hội thoại thực tế và chi tiết.' },
			{ productId: 13001, categories: 'Sách ngoại ngữ', author: 'Huyền Windy', publishingHouse: 'NXB Văn Học', img: 'images/sachngoaingu/5000_Tu_Tieng_Anh_Thong_Dung_Nhat.jpg', name: '5000 Từ tiếng anh thông dụng nhất', price: 352000, description: 'Sách này là hướng dẫn toàn diện với 5000 từ tiếng Anh thông dụng nhất, giúp người học mở rộng vốn từ vựng và nâng cao kỹ năng ngôn ngữ.' },
			{ productId: 13002, categories: 'Sách ngoại ngữ', author: 'Trang Anh', publishingHouse: 'NXB Văn Học', img: 'images/sachngoaingu/Cam_Nang_Cau_Truc_Tieng_Anh.jpg', name: 'Cẩm nang cấu trúc tiếng anh', price: 346000, description: ' "Cẩm nang cấu trúc tiếng Anh" là cuốn sách giúp độc giả hiểu rõ cấu trúc ngữ pháp tiếng Anh thông qua ví dụ và giải thích chi tiết.' },
			{ productId: 13003, categories: 'Sách ngoại ngữ', author: 'Lê Hoàng Dũng', publishingHouse: 'NXB Văn Học', img: 'images/sachngoaingu/CoursebookTiengAnhLop11.jpg', name: 'Tiếng Anh 11', price: 231000, description: '"Tiếng Anh 11" là cuốn sách giáo trình chính cho học sinh lớp 11, cung cấp kiến thức và bài tập phong phú để nâng cao khả năng tiếng Anh của học sinh.' },
			{ productId: 13004, categories: 'Sách ngoại ngữ', author: 'Trần Mạnh Tường', publishingHouse: 'NXB Văn Học', img: 'images/sachngoaingu/Ngu_Phap_Tieng_Anh_Li_Thuyet_Va_Bai_Tap.jpg', name: 'Ngữ pháp tiếng anh', price: 169000, description: '"Ngữ pháp tiếng Anh" là nguồn tài liệu tham khảo quan trọng giúp người học rèn luyện khả năng sử dụng ngữ pháp một cách chính xác và linh hoạt.' },
			{ productId: 13005, categories: 'Sách ngoại ngữ', author: 'Cho Hang Rok', publishingHouse: 'NXB Văn Học', img: 'images/sachngoaingu/tienghan.png', name: 'Tiếng Hàn tổng hợp', price: 257000, description: 'Cuốn sách này giúp học viên tự học tiếng Hàn một cách toàn diện từ vựng, ngữ pháp đến kỹ năng giao tiếp hàng ngày.' },
			{ productId: 13006, categories: 'Sách ngoại ngữ', author: 'Hải Quỳnh', publishingHouse: 'NXB Văn Học', img: 'images/sachngoaingu/tuhoctiengnhat.png', name: 'Tự học tiếng nhật cấp tốc', price: 128000, description: ' "Tự học tiếng Nhật cấp tốc" là cuốn sách hữu ích cho những người muốn tự học tiếng Nhật một cách nhanh chóng và hiệu quả.' },
			{ productId: 13007, categories: 'Sách ngoại ngữ', author: 'Bộ giáo dục và đào tạo', publishingHouse: 'NXB Văn Học', img: 'images/sachngoaingu/tiengtrung.jpg', name: 'Tiếng Trung Quốc 9', price: 364000, description: ' "Tiếng Trung Quốc 9" là sách giáo trình giúp học sinh lớp 9 nắm bắt kiến thức vững về ngữ pháp và từ vựng tiếng Trung.' },
			{ productId: 13008, categories: 'Sách ngoại ngữ', author: 'Du Mẫn Hồng - Nguyễn Thành Yến', publishingHouse: 'NXB Văn Học', img: 'images/sachngoaingu/ielts.jpg', name: 'Enrich your Ielts vocabulary', price: 419000, description: 'Cuốn sách giúp người học IELTS mở rộng vốn từ vựng và nâng cao khả năng sử dụng từ ngữ trong kỳ thi.' },
			{ productId: 13009, categories: 'Sách ngoại ngữ', author: 'Bộ giáo dục và đào tạo', publishingHouse: 'NXB Văn Học', img: 'images/sachngoaingu/tiengtrungnc.jpg', name: 'Tiếng Trung Quốc nâng cao 11', price: 159000, description: ' "Tiếng Trung Quốc nâng cao 11" cung cấp kiến thức tiếng Trung chuyên sâu và bài tập thực hành, phục vụ nhu cầu học tập của học sinh lớp 11.' },
			{ productId: 13010, categories: 'Sách ngoại ngữ', author: 'Nguyễn Thị Hà Bắc', publishingHouse: 'NXB Văn Học', img: 'images/sachngoaingu/hctienganhhieuqua.jpg', name: 'Tự học Tiếng Anh', price: 222000, description: 'Cuốn sách này là hướng dẫn tự học tiếng Anh, giúp độc giả nắm bắt ngữ pháp, từ vựng và kỹ năng giao tiếp một cách hiệu quả.' },
			{ productId: 13011, categories: 'Sách ngoại ngữ', author: 'Trần Hải Quỳnh', publishingHouse: 'NXB Văn Học', img: 'images/sachngoaingu/hoctiengnhat.png', name: 'Tự học Tiếng Nhật dành cho người mới bắt đầu', price: 369000, description: 'Cuốn sách này là nguồn tài liệu hữu ích cho những người mới bắt đầu học tiếng Nhật, giúp họ hiểu rõ về cấu trúc ngôn ngữ và từ vựng cơ bản.' },
			{ productId: 13012, categories: 'Sách ngoại ngữ', author: 'Learn By Heart', publishingHouse: 'NXB Văn Học', img: 'images/sachngoaingu/tienganhphuongphaptunhien.jpg', name: 'Natural English A2', price: 149000, description: '"Natural English A2" là cuốn sách giúp người học tiếng Anh ở trình độ A2 phát triển kỹ năng ngôn ngữ tự nhiên thông qua các hoạt động và bài tập thực hành.' },
			{ productId: 13013, categories: 'Sách ngoại ngữ', author: 'Raymond Tsai', publishingHouse: 'NXB Văn Học', img: 'images/sachngoaingu/tienganhgiaotiep.jpg', name: 'Học Tiếng Anh giao tiếp chỉ trong 30 ngày', price: 155000, description: 'Cuốn sách này hứa hẹn giúp người học tiếng Anh nâng cao kỹ năng giao tiếp trong thời gian ngắn, với phương pháp học hiệu quả.' },
			{ productId: 13014, categories: 'Sách ngoại ngữ', author: 'Hồng Đức', publishingHouse: 'NXB Văn Học', img: 'images/sachngoaingu/2000tutienganh.jpg', name: 'Tự học 2000 từ vựng tiếng anh theo chủ đề', price: 84000, description: 'Cuốn sách cung cấp 2000 từ vựng tiếng Anh theo chủ đề, giúp người học mở rộng vốn từ và sử dụng từ vựng một cách linh hoạt theo ngữ cảnh.' },
			{ productId: 13015, categories: 'Sách ngoại ngữ', author: 'Hoàng Thanh Hải', publishingHouse: 'NXB Văn Học', img: 'images/sachngoaingu/10ngoaingu.jpg', name: 'Cách học 10 ngoại ngữ', price: 277000, description: 'Cuốn sách này chia sẻ cách học đa ngôn ngữ hiệu quả, giúp độc giả tự tin khám phá và nắm bắt nhiều ngôn ngữ khác nhau.' },

		];
		localStorage.setItem('List-products', JSON.stringify(productArray));
	}
}

createProduct();
